default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scratch_api_development
test:
  <<: *default
  database: scratch_api_test

production:
  <<: *default
  database: scratch_api_production
  username: scratch_api
  password: <%= ENV['SCRATCH_API_DATABASE_PASSWORD'] %>
