---
name: Rails Continuous Integration

on:
  pull_request:
    branches: [development]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11@sha256:85d79cba2d4942dad7c99f84ec389a5b9cc84fb07a3dcd3aff0fb06948cdc03b
        env:
          POSTGRES_USER: scratch_api
          POSTGRES_DB: scratch_api_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Create DB
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
        run: |
          bin/rails db:prepare

      - name: Run tests
        run: bundle exec rspec
